COMPANY_TO_TICKER_MAP = {
    'agilent technologies, inc.': 'A',
    'alcoa corporation': 'AA',
    'ata creativity global': 'AACG',
    'ares acquisition corporation ii': 'AACT',
    'aadi bioscience, inc.': 'AADI',
    'african agriculture holdings inc.': 'AAGR',
    'american airlines group inc.': 'AAL',
    'aa mission acquisition corp.': 'AAM',
    'altisource asset management corporation': 'AAMC',
    'atlantic american corporation': 'AAME',
    # 'the aaron's company, inc.': 'AAN',
    'applied optoelectronics, inc.': 'AAOI',
    'aaon, inc.': 'AAON',
    'advance auto parts, inc.': 'AAP',
    'apple': 'AAPL',
    'american assets trust, inc.': 'AAT',
    'alliancebernstein holding l.p.': 'AB',
    'american battery technology company': 'ABAT',
    'abbvie inc.': 'ABBV',
    'ameris bancorp': 'ABCB',
    'abcellera biologics inc.': 'ABCL',
    'abeona therapeutics inc.': 'ABEO',
    'ambev s.a.': 'ABEV',
    'asbury automotive group, inc.': 'ABG',
    'abacus life, inc.': 'ABL',
    'able view global inc.': 'ABLV',
    'abm industries incorporated': 'ABM',
    'airbnb, inc.': 'ABNB',
    'acumen pharmaceuticals, inc.': 'ABOS',
    'arbor realty trust, inc.': 'ABR',
    'absci corporation': 'ABSI',
    'abbott laboratories': 'ABT',
    'abits group inc.': 'ABTS',
    'arbutus biopharma corporation': 'ABUS',
    'abvc biopharma, inc.': 'ABVC',
    'above food ingredients inc.': 'ABVE',
    'abivax soci�t� anonyme': 'ABVX',
    'associated capital group, inc.': 'AC',
    'arcosa, inc.': 'ACA',
    'atlantic coastal acquisition corp. ii': 'ACAB',
    'acri capital acquisition corporation': 'ACAC',
    'acadia pharmaceuticals inc.': 'ACAD',
    'aurora cannabis inc.': 'ACB',
    'accolade, inc.': 'ACCD',
    'acco brands corporation': 'ACCO',
    'profrac holding corp.': 'ACDC',
    'accel entertainment, inc.': 'ACEL',
    'adicet bio, inc.': 'ACET',
    'arch capital group ltd.': 'ACGL',
    'acadia healthcare company, inc.': 'ACHC',
    'achilles therapeutics plc': 'ACHL',
    'archer aviation inc.': 'ACHR',
    'achieve life sciences, inc.': 'ACHV',
    'albertsons companies, inc.': 'ACI',
    'american coastal insurance corporation': 'ACIC',
    'ac immune sa': 'ACIU',
    'aci worldwide, inc.': 'ACIW',
    'axcelis technologies, inc.': 'ACLS',
    'arcellx, inc.': 'ACLX',
    'aecom': 'ACM',
    'acm research, inc.': 'ACMR',
    'accenture plc': 'ACN',
    'acnb corporation': 'ACNB',
    'ascent industries co.': 'ACNT',
    'aclarion, inc.': 'ACON',
    'acres commercial realty corp.': 'ACR',
    'ares commercial real estate corporation': 'ACRE',
    'aclaris therapeutics, inc.': 'ACRS',
    'acrivon therapeutics, inc.': 'ACRV',
    'acasti pharma inc.': 'ACST',
    'enact holdings, inc.': 'ACT',
    'acacia research corporation': 'ACTG',
    'actuate therapeutics, inc.': 'ACTU',
    'acme united corporation': 'ACU',
    'acv auctions inc.': 'ACVA',
    'acurx pharmaceuticals, inc.': 'ACXP',
    'adagene inc.': 'ADAG',
    'adaptimmune therapeutics plc': 'ADAP',
    'adobe inc.': 'ADBE',
    'agree realty corporation': 'ADC',
    'adc therapeutics sa': 'ADCT',
    'color star technology co., ltd.': 'ADD',
    'adeia inc.': 'ADEA',
    'adagio medical holdings, inc.': 'ADGM',
    'analog devices, inc.': 'ADI',
    'adial pharmaceuticals, inc.': 'ADIL',
    'archer-daniels-midland company': 'ADM',
    'adma biologics, inc.': 'ADMA',
    'advent technologies holdings, inc.': 'ADN',
    'adient plc': 'ADNT',
    'automatic data processing, inc.': 'ADP',
    'adaptive biotechnologies corporation': 'ADPT',
    'ault disruptive technologies corporation': 'ADRT',
    'ads-tec energy plc': 'ADSE',
    'autodesk, inc.': 'ADSK',
    'adt inc.': 'ADT',
    'adtran holdings, inc.': 'ADTN',
    'aditxt, inc.': 'ADTX',
    'addus homecare corporation': 'ADUS',
    'advantage solutions inc.': 'ADV',
    'adverum biotechnologies, inc.': 'ADVM',
    'addex therapeutics ltd': 'ADXN',
    'adams resources & energy, inc.': 'AE',
    'altenergy acquisition corp.': 'AEAE',
    'ameren corporation': 'AEE',
    'aegon ltd.': 'AEG',
    'antelope enterprise holdings limited': 'AEHL',
    'aehr test systems, inc.': 'AEHR',
    'alset inc.': 'AEI',
    'advanced energy industries, inc.': 'AEIS',
    'agnico eagle mines limited': 'AEM',
    'aethlon medical, inc.': 'AEMD',
    'alliance entertainment holding corporation': 'AENT',
    'american eagle outfitters, inc.': 'AEO',
    'aeon biopharma, inc.': 'AEON',
    'american electric power company, inc.': 'AEP',
    'aercap holdings n.v.': 'AER',
    'aeries technology, inc': 'AERT',
    'the aes corporation': 'AES',
    'atlas energy solutions inc.': 'AESI',
    'aeva technologies, inc.': 'AEVA',
    'audioeye, inc.': 'AEYE',
    'aura fat projects acquisition corp': 'AFAR',
    'affinity bancshares, inc.': 'AFBI',
    'afc gamma, inc.': 'AFCG',
    'american financial group, inc.': 'AFG',
    'aimei health technology co., ltd': 'AFJK',
    'aflac incorporated': 'AFL',
    'affimed n.v.': 'AFMD',
    'forafric global plc': 'AFRI',
    'affirm holdings, inc.': 'AFRM',
    'afya limited': 'AFYA',
    'first majestic silver corp.': 'AG',
    'allied gaming & entertainment inc.': 'AGAE',
    'agba group holding limited': 'AGBA',
    'agco corporation': 'AGCO',
    'agenus inc.': 'AGEN',
    'agrify corporation': 'AGFY',
    'alamos gold inc.': 'AGI',
    'agios pharmaceuticals, inc.': 'AGIO',
    'agilon health, inc.': 'AGL',
    'federal agricultural mortgage corporation': 'AGM.A',
    'agm group holdings inc.': 'AGMH',
    'agnc investment corp.': 'AGNC',
    'assured guaranty ltd.': 'AGO',
    'avangrid, inc.': 'AGR',
    'agriforce growing systems ltd.': 'AGRI',
    'adecoagro s.a.': 'AGRO',
    'playags, inc.': 'AGS',
    'argan, inc.': 'AGX',
    'agilysys, inc.': 'AGYS',
    'adapthealth corp.': 'AHCO',
    'akso health group': 'AHG',
    'armada hoffler properties, inc.': 'AHH',
    'american healthcare reit, inc.': 'AHR',
    'ashford hospitality trust, inc.': 'AHT',
    'c3.ai, inc.': 'AI',
    'thunder power holdings, inc.': 'AIEV',
    'firefly neuroscience, inc.': 'AIFF',
    'american international group, inc.': 'AIG',
    'senmiao technology limited': 'AIHS',
    'ilearningengines, inc.': 'AILE',
    'aim immunotech inc.': 'AIM',
    'aimfinity investment corp. i': 'AIMAU',
    'ainos, inc.': 'AIMD',
    'albany international corp.': 'AIN',
    'powerfleet, inc.': 'AIOT',
    'arteris, inc.': 'AIP',
    'aar corp.': 'AIR',
    'realpha tech corp.': 'AIRE',
    'airgain, inc.': 'AIRG',
    'air industries group': 'AIRI',
    'montana technologies corporation': 'AIRJ',
    'airsculpt technologies, inc.': 'AIRS',
    'air t, inc.': 'AIRT',
    'airship ai holdings, inc.': 'AISP',
    'applied industrial technologies, inc.': 'AIT',
    'ai transportation acquisition corp': 'AITR',
    'apartment investment and management company': 'AIV',
    'xiao-i corporation': 'AIXI',
    'assurant, inc.': 'AIZ',
    'arthur j. gallagher & co.': 'AJG',
    'great ajax corp.': 'AJX',
    'a.k.a. brands holding corp.': 'AKA',
    'akamai technologies, inc.': 'AKAM',
    'akanda corp.': 'AKAN',
    'akebia therapeutics, inc.': 'AKBA',
    'embotelladora andina s.a.': 'AKO.B',
    'acadia realty trust': 'AKR',
    'akero therapeutics, inc.': 'AKRO',
    'akoustis technologies, inc.': 'AKTS',
    'akari therapeutics, plc': 'AKTX',
    'akoya biosciences, inc.': 'AKYA',
    'air lease corporation': 'AL',
    'astera labs, inc.': 'ALAB',
    'alarum technologies ltd.': 'ALAR',
    'albemarle corporation': 'ALB',
    'avalon globocare corp.': 'ALBT',
    'alcon inc.': 'ALC',
    'alternus clean energy inc': 'ALCE',
    'alico, inc.': 'ALCO',
    'alchemy investments acquisition corp 1': 'ALCY',
    'aldeyra therapeutics, inc.': 'ALDX',
    'allete, inc.': 'ALE',
    'alector, inc.': 'ALEC',
    'alexander & baldwin, inc.': 'ALEX',
    'centurion acquisition corp.': 'ALF',
    'alamo group inc.': 'ALG',
    'allegro microsystems, inc.': 'ALGM',
    'align technology, inc.': 'ALGN',
    'aligos therapeutics, inc.': 'ALGS',
    'allegiant travel company': 'ALGT',
    'alignment healthcare, inc.': 'ALHC',
    'alimera sciences, inc.': 'ALIM',
    'alight, inc.': 'ALIT',
    'alaska air group, inc.': 'ALK',
    'alkermes plc': 'ALKS',
    'alkami technology, inc.': 'ALKT',
    'the allstate corporation': 'ALL',
    'allegion plc': 'ALLE',
    'allakos inc.': 'ALLK',
    'allogene therapeutics, inc.': 'ALLO',
    'allarity therapeutics, inc.': 'ALLR',
    'allot ltd.': 'ALLT',
    'ally financial inc.': 'ALLY',
    'alumis inc.': 'ALMS',
    'allient inc.': 'ALNT',
    'alnylam pharmaceuticals, inc.': 'ALNY',
    'astronova, inc.': 'ALOT',
    'alpine 4 holdings, inc.': 'ALPP',
    'alarm.com holdings, inc.': 'ALRM',
    'aileron therapeutics, inc.': 'ALRN',
    'alerus financial corporation': 'ALRS',
    'alpha star acquisition corporation': 'ALSA',
    'allison transmission holdings, inc.': 'ALSN',
    'altimmune, inc.': 'ALT',
    'alta equipment group inc.': 'ALTG',
    'alti global, inc.': 'ALTI',
    'arcadium lithium plc': 'ALTM',
    'alto ingredients, inc.': 'ALTO',
    'altair engineering inc.': 'ALTR',
    'alt5 sigma corporation': 'ALTS',
    'allurion technologies inc.': 'ALUR',
    'autoliv, inc.': 'ALV',
    'alvotech': 'ALVO',
    'allovir, inc.': 'ALVR',
    # 'alexander's, inc.': 'ALX',
    'alx oncology holdings inc.': 'ALXO',
    'alzamend neuro, inc.': 'ALZN',
    'antero midstream corporation': 'AM',
    'amalgamated financial corp.': 'AMAL',
    'applied materials, inc.': 'AMAT',
    'ambarella, inc.': 'AMBA',
    'ambac financial group, inc.': 'AMBC',
    'ambipar emergency response': 'AMBI',
    'ambow education holding ltd.': 'AMBO',
    'ardagh metal packaging s.a.': 'AMBP',
    'amc entertainment holdings, inc.': 'AMC',
    'amcor plc': 'AMCR',
    'amc networks inc.': 'AMCX',
    'advanced micro devices, inc.': 'AMD',
    'ametek, inc.': 'AME',
    'amedisys, inc.': 'AMED',
    'affiliated managers group, inc.': 'AMG',
    'amgen inc.': 'AMGN',
    'american homes 4 rent': 'AMH',
    'autonomix medical, inc.': 'AMIX',
    'amkor technology, inc.': 'AMKR',
    'american lithium corp.': 'AMLI',
    'amylyx pharmaceuticals, inc.': 'AMLX',
    'amn healthcare services, inc.': 'AMN',
    'ameriprise financial, inc.': 'AMP',
    'amplitech group, inc.': 'AMPG',
    'amphastar pharmaceuticals, inc.': 'AMPH',
    'amplitude, inc.': 'AMPL',
    'altus power, inc.': 'AMPS',
    'amprius technologies, inc.': 'AMPX',
    'amplify energy corp.': 'AMPY',
    'alpha metallurgical resources, inc.': 'AMR',
    'ameresco, inc.': 'AMRC',
    'a-mark precious metals, inc.': 'AMRK',
    'amarin corporation plc': 'AMRN',
    'amneal pharmaceuticals, inc.': 'AMRX',
    'american shared hospital services': 'AMS',
    'american superconductor corporation': 'AMSC',
    'amerisafe, inc.': 'AMSF',
    'amesite inc.': 'AMST',
    'american software, inc.': 'AMSWA',
    'american tower corporation': 'AMT',
    'amerant bancorp inc.': 'AMTB',
    'amtd idea group': 'AMTD',
    'aemetis, inc.': 'AMTX',
    'american woodmark corporation': 'AMWD',
    'american well corporation': 'AMWL',
    'am�rica m�vil, s.a.b. de c.v.': 'AMX',
    'amazon.com, inc.': 'AMZN',
    'autonation, inc.': 'AN',
    'anaptysbio, inc.': 'ANAB',
    'the andersons, inc.': 'ANDE',
    'anebulo pharmaceuticals, inc.': 'ANEB',
    'arista networks, inc.': 'ANET',
    'abercrombie & fitch co.': 'ANF',
    'anghami inc.': 'ANGH',
    'angi inc.': 'ANGI',
    'angiodynamics, inc.': 'ANGO',
    'anika therapeutics, inc.': 'ANIK',
    'ani pharmaceuticals, inc.': 'ANIP',
    'anixa biosciences, inc.': 'ANIX',
    'adlai nortye ltd.': 'ANL',
    'annexon, inc.': 'ANNX',
    'alto neuroscience, inc.': 'ANRO',
    'agriculture & natural solutions acquisition corporation': 'ANSC',
    'ansys, inc.': 'ANSS',
    'airnet technology inc.': 'ANTE',
    'an2 therapeutics, inc.': 'ANTX',
    'annovis bio, inc.': 'ANVS',
    'sphere 3d corp.': 'ANY',
    'arogo capital acquisition corp.': 'AOGO',
    'angel oak mortgage reit, inc.': 'AOMR',
    'aon plc': 'AON',
    'artivion, inc.': 'AORT',
    'a. o. smith corporation': 'AOS',
    'alpha and omega semiconductor limited': 'AOSL',
    'american outdoor brands, inc.': 'AOUT',
    'ampco-pittsburgh corporation': 'AP',
    'apa corporation': 'APA',
    'artisan partners asset management inc.': 'APAM',
    'apptech payments corp.': 'APCX',
    'air products and chemicals, inc.': 'APD',
    'applied dna sciences, inc.': 'APDN',
    'american public education, inc.': 'APEI',
    'api group corporation': 'APG',
    'apogee therapeutics, inc.': 'APGE',
    'amphenol corporation': 'APH',
    'agora, inc.': 'API',
    'applied digital corporation': 'APLD',
    'apple hospitality reit, inc.': 'APLE',
    'apollomics, inc.': 'APLM',
    'apellis pharmaceuticals, inc.': 'APLS',
    'applied therapeutics, inc.': 'APLT',
    'aptorum group limited': 'APM',
    'apollo global management, inc.': 'APO',
    'apogee enterprises, inc.': 'APOG',
    'applovin corporation': 'APP',
    'appfolio, inc.': 'APPF',
    'appian corporation': 'APPN',
    'digital turbine, inc.': 'APPS',
    'aprea therapeutics, inc.': 'APRE',
    'alpha pro tech, ltd.': 'APT',
    'aptose biosciences inc.': 'APTO',
    'aptiv plc': 'APTV',
    'aptevo therapeutics inc.': 'APVO',
    'asia pacific wire & cable corporation limited': 'APWC',
    'apx acquisition corp. i': 'APXI',
    'apyx medical corporation': 'APYX',
    'aquabounty technologies, inc.': 'AQB',
    'aqua metals, inc.': 'AQMS',
    'algonquin power & utilities corp.': 'AQN',
    'aquestive therapeutics, inc.': 'AQST',
    'aquaron acquisition corp.': 'AQU',
    'antero resources corporation': 'AR',
    'accuray incorporated': 'ARAY',
    'arb iot group limited': 'ARBB',
    'arbe robotics ltd.': 'ARBE',
    'argo blockchain plc': 'ARBK',
    'arc document solutions, inc.': 'ARC',
    'arcbest corporation': 'ARCB',
    'ares capital corporation': 'ARCC',
    'arch resources, inc.': 'ARCH',
    'arcos dorados holdings inc.': 'ARCO',
    'arcturus therapeutics holdings inc.': 'ARCT',
    'ardent health partners, inc.': 'ARDT',
    'ardelyx, inc.': 'ARDX',
    'alexandria real estate equities, inc.': 'ARE',
    'american rebel holdings, inc.': 'AREB',
    'american resources corporation': 'AREC',
    'the arena group holdings, inc.': 'AREN',
    'ares management corporation': 'ARES',
    'argenx se': 'ARGX',
    'arhaus, inc.': 'ARHS',
    'apollo commercial real estate finance, inc.': 'ARI',
    'aris water solutions, inc.': 'ARIS',
    'arko corp.': 'ARKO',
    'ark restaurants corp.': 'ARKR',
    'american realty investors, inc.': 'ARL',
    'arlo technologies, inc.': 'ARLO',
    'alliance resource partners, l.p.': 'ARLP',
    'arm holdings plc': 'ARM',
    'aramark': 'ARMK',
    'aris mining corporation': 'ARMN',
    'armata pharmaceuticals, inc.': 'ARMP',
    'archrock, inc.': 'AROC',
    'arrow financial corporation': 'AROW',
    'arq, inc.': 'ARQ',
    'arqit quantum inc.': 'ARQQ',
    'arcutis biotherapeutics, inc.': 'ARQT',
    'armour residential reit, inc.': 'ARR',
    'array technologies, inc.': 'ARRY',
    'artelo biosciences, inc.': 'ARTL',
    'artesian resources corporation': 'ARTNA',
    'artiva biotherapeutics, inc.': 'ARTV',
    # 'art's-way manufacturing co., inc.': 'ARTW',
    'arvinas, inc.': 'ARVN',
    'arrow electronics, inc.': 'ARW',
    'arrowhead pharmaceuticals, inc.': 'ARWR',
    'amer sports, inc.': 'AS',
    'asa gold and precious metals limited': 'ASA',
    'sendas distribuidora s.a.': 'ASAI',
    'asana, inc.': 'ASAN',
    'associated banc-corp': 'ASB',
    'ardmore shipping corporation': 'ASC',
    'a spac ii acquisition corp.': 'ASCB',
    'asgn incorporated': 'ASGN',
    'ashland inc.': 'ASH',
    'advansix inc.': 'ASIX',
    'aersale corporation': 'ASLE',
    'avino silver & gold mines ltd.': 'ASM',
    'assembly biosciences, inc.': 'ASMB',
    'asml holding n.v.': 'ASML',
    'ascendis pharma a/s': 'ASND',
    'actelis networks, inc.': 'ASNS',
    'academy sports and outdoors, inc.': 'ASO',
    'asp isotopes inc.': 'ASPI',
    'aspen aerogels, inc.': 'ASPN',
    'altisource portfolio solutions s.a.': 'ASPS',
    'grupo aeroportuario del sureste, s. a. b. de c. v.': 'ASR',
    'assertio holdings, inc.': 'ASRT',
    'ameriserv financial, inc.': 'ASRV',
    'asset entities inc.': 'ASST',
    'astrotech corporation': 'ASTC',
    'astec industries, inc.': 'ASTE',
    'astrana health, inc.': 'ASTH',
    'ascent solar technologies, inc.': 'ASTI',
    'algoma steel group inc.': 'ASTL',
    'ast spacemobile, inc.': 'ASTS',
    'asure software, inc.': 'ASUR',
    'ase technology holding co., ltd.': 'ASX',
    'amtech systems, inc.': 'ASYS',
    'atai life sciences n.v.': 'ATAI',
    'atour lifestyle holdings limited': 'ATAT',
    'atlasclear holdings, inc.': 'ATCH',
    'alphatec holdings, inc.': 'ATEC',
    'athena technology acquisition corp. ii': 'ATEK',
    'a10 networks, inc.': 'ATEN',
    'aterian, inc.': 'ATER',
    'anterix inc.': 'ATEX',
    'adtalem global education inc.': 'ATGE',
    'alpha technology group limited': 'ATGL',
    'athira pharma, inc.': 'ATHA',
    'alterity therapeutics limited': 'ATHE',
    'autohome inc.': 'ATHM',
    'ati inc.': 'ATI',
    'atif holdings limited': 'ATIF',
    'ati physical therapy, inc.': 'ATIP',
    'atkore inc.': 'ATKR',
    'atlanticus holdings corporation': 'ATLC',
    'ames national corporation': 'ATLO',
    'atlas lithium corporation': 'ATLX',
    'alphatime acquisition corp': 'ATMC',
    'atmus filtration technologies inc.': 'ATMU',
    'alphavest acquisition corp': 'ATMV',
    '180 life sciences corp.': 'ATNF',
    'atn international, inc.': 'ATNI',
    'actinium pharmaceuticals, inc.': 'ATNM',
    'atmos energy corporation': 'ATO',
    'atomera incorporated': 'ATOM',
    'atossa therapeutics, inc.': 'ATOS',
    'agape atp corporation': 'ATPC',
    'aptargroup, inc.': 'ATR',
    'atara biotherapeutics, inc.': 'ATRA',
    'atricure, inc.': 'ATRC',
    'astronics corporation': 'ATRO',
    'ats corporation': 'ATS',
    'air transport services group, inc.': 'ATSG',
    'altice usa, inc.': 'ATUS',
    'addentax group corp.': 'ATXG',
    'avenue therapeutics, inc.': 'ATXI',
    'astria therapeutics, inc.': 'ATXS',
    'atyr pharma, inc.': 'ATYR',
    'anglogold ashanti plc': 'AU',
    'atlantic union bankshares corporation': 'AUB',
    'auburn national bancorporation, inc.': 'AUBN',
    'audiocodes ltd.': 'AUDC',
    'augmedix, inc.': 'AUGX',
    'authid inc.': 'AUID',
    'ault alliance, inc.': 'AULT',
    'golden minerals company': 'AUMN',
    'auna s.a.': 'AUNA',
    'aurinia pharmaceuticals inc.': 'AUPH',
    'aurora innovation, inc.': 'AUR',
    'aura biosciences, inc.': 'AURA',
    'austin gold corp.': 'AUST',
    'autolus therapeutics plc': 'AUTL',
    'auddia inc.': 'AUUD',
    'avista corporation': 'AVA',
    'aveanna healthcare holdings inc.': 'AVAH',
    'grupo aval acciones y valores s.a.': 'AVAL',
    'aerovironment, inc.': 'AVAV',
    'microsoft': 'MSFT',
    'google': 'GOOG',
    'amazon': 'AMZN',
    'facebook': 'META',
    'tesla': 'TSLA',
    'solaredge technologies': 'SEDG',
    'wolfspeed': 'WOLF',
    'general electric': 'GE',
    'General Electric Company': 'GE',
    'citigroup': 'C',
    'Citigroup, Inc.': 'C',
    'walmart stores': 'WMT',
    'Wal-Mart Stores, Inc.': 'WMT',
    'toyota': 'TM',
    'Toyota Motor Corporation': 'TM',
    'bank of america': 'BAC',
    'Bank of America Corporation': 'BAC',
    'J.P. morgan chase': 'JPM',
    'J.P. Morgan Chase & Co': 'JPM',
    'vodafone': 'VOD',
    'Vodafone AirTouch Public Limited Company': 'VOD',
    'intel': 'INTC',
    'Intel Corporation': 'INTC',
    'cisco': 'CSCO',
    'Cisco Systems, Inc.': 'CSCO',
    'berkshire hathaway': 'BRK/A',
    'Berkshire Hathaway Inc.': 'BRK/A',
    'ubs': 'UBS',
    'UBS AG': 'UBS',
    'wells fargo': 'WFC',
    'Wells Fargo Cap IX': 'WFC',
    'coca cola': 'KO',
    'Coca-Cola Company': 'KO',
    'pepsi': 'PEP',
    'Pepsico, Inc.': 'PEP',
    'hewlett packard': 'HPQ',
    'Hewlett-Packard Company': 'HPQ',
    'nokia': 'NOK',
    'Nokia Corporation': 'NOK',
    'barclays': 'BCS',
    'Barclays PLC': 'BCS',
    'dell': 'DELL',
    'Dell Inc.': 'DELL',
    'american express': 'AXP',
    'American Express Company': 'AXP',
    'morgan stanley': 'MS',
    'oracle': 'ORCL',
    'Oracle Corporation': 'ORCL',
    'goldman sachs': 'GS',
    'Goldman Sachs Group, Inc.': 'GS',
    'eBay': 'EBAY',
    'eBay Inc.': 'EBAY',
    'deutsche bank': 'DB',
    'Deutsche Bank AG': 'DB',
    'motorola': 'MOT',
    'Motorola, Inc.': 'MOT',
    'boeing': 'BA',
    'Boeing Company': 'BA',
    'canon': 'CAJ',
    'Canon, Inc.': 'CAJ',
    'nissan': 'NSANY',
    'Nissan Motor Co., Ltd.': 'NSANY',
    'sony' : 'SNE',
    'yahoo': 'YHOO',
    'walt disney': 'DIS',
    'Walt Disney Company': 'DIS',
    'McDonald': 'MCD',
    'McDonald Corporation': 'MCD',
    'unilever': 'UN',
    'Unilever NV': 'UN',
    'metlife': 'MET',
    'MetLife, Inc. ': 'MET',
    'fedex': 'FDX',
    'FedEx Corporation': 'FDX',
    'Unilever PLC': 'UL',
    'viacom': 'VIA/B',
    'Viacom, Inc.': 'VIA/B',
    'baker hughes': 'BHI',
    'Baker Hughes Incorporated': 'BHI',
    'apache': 'APA',
    'Apache Corporation': 'APA',
    'bank of new york': 'BK',
    'Bank of New York Company, Inc.': 'BK',
    'starbucks' : 'SBUX',
    'Starbucks Corporation': 'SBUX',
    'adobe': 'ADBE',
    'Adobe Systems Incorporated': 'ADBE',
    'htachi': 'HIT',
    'Hitachi, Ltd': 'HIT',
    'NASDAQ-100 Index Tracking Stock': 'QQQQ',
    'wipro': 'WIT',
    'Wipro Limited': 'WIT',
    'cadbury' : 'CSG',
    'Cadbury Schweppes': 'CSG',
    'infosys': 'INFY',
    'Infosys Technologies Limited': 'INFY',
    'stryker': 'SYK',
    'Stryker Corporation': 'SYK',
    'marvell technology' : 'MRVL',
    'Marvell Technology Group, Ltd.': 'MRVL',
    'accenture': 'ACN',
    'Accenture Ltd.': 'ACN',
    'mcgraw hill': 'MHP',
    'McGraw-Hill Companies, Inc.': 'MHP',
    'chubb': 'CB',
    'Chubb Corporation': 'CB',
    'CBS Corporation': 'CBS',
    'kellogg': 'K',
    'Kellogg Company': 'K',
    'nike': 'NKE',
    'Nike, Inc.': 'NKE',
    'ford motors': 'F',
    'ford motor': 'F',
    'Ford Motor Credit Company': 'F',
    'nexen' : 'NXY',
    'Nexen, Inc': 'NXY',
    'reynolds' : 'RAI',
    'REYNOLDS AMERICAN INC': 'RAI',
    'harley davidson': 'HDI',
    'Harley-Davidson, Inc.': 'HDI',
    'AB Volvo': 'VOLVY',
    'icici bank': 'IBN',
    'ICICI Bank Limited': 'IBN',
    'SanDisk': 'SNDK',
    'sandisk': 'SNDK',
    'sanDisk': 'SNDK',
    'SanDisk Corporation': 'SNDK',
    'EQUITY RESIDENTIAL': 'EQR',
    'FORD MTR CO DEL': 'F^A',
    'autodesk': 'ADSK',
    'Autodesk, Inc.': 'ADSK',
    'coca cola enterprises': 'CCE',
    'Coca-Cola Enterprises, Inc.': 'CCE',
    'intuit': 'INTU',
    'Intuit Inc.': 'INTU',
    'rockwell collins': 'COL',
    'Rockwell Collins, Inc': 'COL',
    'Microchip Technology Incorporated': 'MCHP',
    'microchip techonology': 'MCHP',
    'NVIDIA' : 'NVDA',
    'nvdia': 'NVDA',
    'NVIDIA Corporation': 'NVDA',
    'Pepsi Bottling Group, Inc.' : 'PBG',
    'pixar': 'PIXR',
    'Pixar': 'PIXR',
    'Fidelity National Financial': 'FNF',
    'fidelity': 'FNF',
    'Fidelity': 'FNF',
    'HDFC': 'HDB',
    'HDFC Bank Limited': 'HDB',
    'tata motors' : 'TTM',
    'Tata Motors Ltd': 'TTM',
    'omnicare': 'OCR',
    'Omnicare, Inc.' : 'OCR',
    'whirlpool': 'WHR',
    'Whirlpool Corporation': 'WHR',
    'salesforce': 'CRM',
    'Salesforce.com Inc': 'CRM',
    'new york times': 'NYT',
    'New York Times': 'NYT',
    'New York Times Company': 'NYT',
    'DPL Inc.': 'DPL',
    'dpl': 'DPL',
    'sabre': 'TSG',
    'Sabre Holdings Corporation': 'TSG',
    'AVX': 'AVX',
    'AVX Corporation': 'AVX',
    'Shaw Group Inc.': 'SGR',
    'blackrock': 'BLK',
    'BlackRock': 'BLK',
    'BlackRock, Inc.': 'BLK',
    'Marvel Enterprises': 'MVL',
    'Marvel Enterprises': 'MVL',
    'Marvel Enterprises, Inc.': 'MVL',
    'tupperware': 'TUP',
    'Tupperware': 'TUP',
    'Tupperware Corporation': 'TUP',
}
